name: venus

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.3.0"

flutter:
  uses-material-design: true
  assets:
    - static/images/
    - static/images/icons/
    - static/images/placeholder/
    - static/sql/

dependencies:
  flutter:
    sdk: flutter
  http:
  provider: ^6.0.5
  path: ^1.8.2
  flutter_svg: ^1.1.6
  uuid: ^3.0.7
  syncfusion_flutter_datepicker: ^20.4.42
  syncfusion_flutter_calendar: ^20.4.42
  url_strategy: ^0.2.0
  validators: ^3.0.0
  quantum_sqlite: ^0.1.1
  split_view: ^3.1.0
  flutter_riverpod: ^2.1.3
  flutter_screenutil: ^5.6.0
  json_annotation: ^4.7.0
  flutter_staggered_grid_view: ^0.6.2
  markdown: ^6.0.1
  flutter_highlight: ^0.7.0
  markdown_widget: ^1.3.0+2
  loading_indicator: ^3.1.0
  mime: ^1.0.3
  file_picker: ^5.2.4
  path_provider: ^2.0.11
  go_router: ^6.0.1
  sqlite3: ^1.9.1

dev_dependencies:
  flutter_lints:
  build_runner: any
  json_serializable: ^6.5.1 
